### PR TITLE
Added rudimentary FreeBSD support via GCC toolchain.

### PR DESCRIPTION
**Pull request by p-kraszewski**
Tested on:
* FreeBSD 13.0-RELEASE-p4
* erlang-21.3.8.24_1,4
* elixir-1.11.3
* gcc-10_4

with not that simple NIF project.

TODO: migrate GCC to clang - I have to yet put together the necessary, correct flags.

### CODE REVIEW

**Comment by mat-hek** [comment]
Thanks for this ;) let me know when migration to clang is done

**Comment by p-kraszewski** [comment]
Here you are.

It was simpler than I thought.

**Comment by mat-hek** [comment]
LGTM, don't have the possibility to test it quickly, so I believe it works for you and you verified that the tests are passing :) Please format the code and we can merge

**Comment by p-kraszewski** [comment]
Dzięki, miłego dnia!

**Pull request merged**
